INSERT INTO tasks_food (id, user_id, condition_key, name, tip, icon, display_order) VALUES 
('seed_sugg_101', NULL, 'general', 'Drink 8-10 glasses', 'Drink 8-10 glasses (2.5 to 3 Liters) of clean, fresh water across the day.', '🥗', 102),
('seed_sugg_102', NULL, 'general', 'Incorporate whole grains', 'Incorporate whole grains (brown rice, oats, whole wheat) and sprouted legumes.', '🥗', 103),
('seed_sugg_103', NULL, 'general', 'Prefer balanced, freshly cooked wholesome home meals.', '', '🥗', 104),
('seed_sugg_104', NULL, 'general', 'Avoid excess salt and refined sugar which spike blood pressure and glucose.', 'Avoid excess salt and refined sugar which spike blood pressure and glucose.', '🛑', 105),
('seed_sugg_105', NULL, 'general', 'Avoid processed foods', 'Avoid processed foods, deep-fried snacks, and heavy artificial preservatives.', '🛑', 106),
('seed_sugg_106', NULL, 'general', 'Reduce intake of aerated drinks', 'Reduce intake of aerated drinks, excessive caffeine, and energy drinks.', '🛑', 107),
('seed_sugg_116', NULL, 'digestion', 'Eat warm', 'Eat warm, freshly cooked foods that are easy to digest (soups, khichdi).', '🥗', 117),
('seed_sugg_117', NULL, 'digestion', 'Include cooling and soothing foods like yogurt', 'Include cooling and soothing foods like yogurt, buttermilk, and fennel seeds.', '🥗', 118),
('seed_sugg_118', NULL, 'digestion', 'Drink warm water or cumin-coriander tea throughout the day.', 'Drink warm water or cumin-coriander tea throughout the day.', '🥗', 119),
('seed_sugg_120', NULL, 'digestion', 'Strictly avoid heavily spiced', 'Strictly avoid heavily spiced, deep-fried, and overly oily foods.', '🛑', 121),
('seed_sugg_122', NULL, 'digestion', 'Do not drink chilled iced water', 'Do not drink chilled iced water, especially during or immediately after meals.', '🛑', 123),
('seed_sugg_123', NULL, 'digestion', 'Avoid lying down completely flat immediately after a heavy meal.', 'Avoid lying down completely flat immediately after a heavy meal.', '🛑', 124),
('seed_sugg_125', NULL, 'digestion', 'Practice Vajrasana', 'Practice Vajrasana (Diamond Pose) for 5-10 minutes after eating.', '🥗', 126),
('seed_sugg_129', NULL, 'digestion', 'Maintain fixed meal timings to stabilize digestive rhythms.', 'Maintain fixed meal timings to stabilize digestive rhythms.', '🥗', 130),
('seed_sugg_131', NULL, 'digestion', 'Avoid talking excessively or watching intense TV while eating.', 'Avoid talking excessively or watching intense TV while eating.', '🥗', 132),
('seed_sugg_132', NULL, 'weight', 'Prioritize high-fiber foods', 'Prioritize high-fiber foods (leafy greens, millets, oats, chia seeds).', '🥗', 133),
('seed_sugg_133', NULL, 'weight', 'Ensure sufficient lean protein in every meal to preserve muscle and satiety.', 'Ensure sufficient lean protein in every meal to preserve muscle and satiety.', '🥗', 134),
('seed_sugg_134', NULL, 'weight', 'Drink a glass of warm water 20 minutes before meals to prevent overeating.', 'Drink a glass of warm water 20 minutes before meals to prevent overeating.', '🥗', 135),
('seed_sugg_136', NULL, 'weight', 'Strictly avoid refined carbs', 'Strictly avoid refined carbs (white bread, pastries, sugary sweets).', '🛑', 137),
('seed_sugg_139', NULL, 'weight', 'Limit highly processed packaged foods with hidden trans fats.', 'Limit highly processed packaged foods with hidden trans fats.', '🛑', 140),
('seed_sugg_149', NULL, 'stress', 'Include Omega-3 rich foods', 'Include Omega-3 rich foods (walnuts, flaxseeds) which support brain health.', '🥗', 150),
('seed_sugg_151', NULL, 'stress', 'Eat complex carbohydrates', 'Eat complex carbohydrates (sweet potatoes, oats) to stabilize serotonin levels.', '🥗', 152),
('seed_sugg_152', NULL, 'stress', 'Avoid excessive caffeine', 'Avoid excessive caffeine (coffee, strong tea) which can trigger anxiety and jitters.', '🛑', 153),
('seed_sugg_154', NULL, 'stress', 'Avoid skipping meals', 'Avoid skipping meals, which causes blood sugar drops and mood swings.', '🛑', 155),
('seed_sugg_155', NULL, 'stress', 'Reduce high-sugar foods that cause rapid energy spikes and crashes.', 'Reduce high-sugar foods that cause rapid energy spikes and crashes.', '🛑', 156),
('seed_sugg_158', NULL, 'stress', 'Practice deep diaphragmatic breathing', 'Practice deep diaphragmatic breathing (4-7-8 technique) or Pranayama.', '🥗', 159),
('seed_sugg_166', NULL, 'sleep', 'Include foods naturally high in melatonin', 'Include foods naturally high in melatonin (tart cherries, walnuts).', '🥗', 167),
('seed_sugg_167', NULL, 'sleep', 'Eat complex carbs at night to promote tryptophan transport to the brain.', 'Eat complex carbs at night to promote tryptophan transport to the brain.', '🥗', 168),
('seed_sugg_168', NULL, 'sleep', 'Strictly avoid caffeine, tea, and chocolate after 4 PM.', '', '🛑', 169),
('seed_sugg_181', NULL, 'joints', 'Eat Omega-3 rich foods', 'Eat Omega-3 rich foods (flaxseeds, walnuts) to lubricate joints.', '🥗', 182),
('seed_sugg_183', NULL, 'joints', 'Maintain adequate Calcium and Vitamin D', 'Maintain adequate Calcium and Vitamin D (milk, fortified foods, sunlight).', '🥗', 184),
('seed_sugg_184', NULL, 'joints', 'Avoid refined sugars and trans fats which actively trigger joint inflammation.', 'Avoid refined sugars and trans fats which actively trigger joint inflammation.', '🛑', 185),
('seed_sugg_185', NULL, 'joints', 'Limit red meat and highly processed meats which increase uric acid.', 'Limit red meat and highly processed meats which increase uric acid.', '🛑', 186),
('seed_sugg_186', NULL, 'joints', 'Avoid excessive salt intake which can cause cellular fluid retention.', 'Avoid excessive salt intake which can cause cellular fluid retention.', '🛑', 187),
('seed_sugg_196', NULL, 'sugar_bp', 'Base meals on low Glycemic Index', 'Base meals on low Glycemic Index (GI) foods (beans, lentils, non-starchy veggies).', '🥗', 197),
('seed_sugg_197', NULL, 'sugar_bp', 'Increase potassium-rich foods', 'Increase potassium-rich foods (bananas, spinach) to help manage blood pressure.', '🥗', 198),
('seed_sugg_199', NULL, 'sugar_bp', 'Use garlic and cinnamon', 'Use garlic and cinnamon, which have mild BP and sugar-lowering properties.', '🥗', 200),
('seed_sugg_200', NULL, 'sugar_bp', 'Strictly avoid table sugar', 'Strictly avoid table sugar, jaggery, honey, and refined white flour (Maida).', '🛑', 201),
('seed_sugg_201', NULL, 'sugar_bp', 'Strictly limit sodium/salt intake', 'Strictly limit sodium/salt intake (avoid pickles, papads, canned foods).', '🛑', 202),
('seed_sugg_203', NULL, 'sugar_bp', 'Do not skip meals', 'Do not skip meals; eat at regular, spaced intervals to prevent hypoglycemia.', '🛑', 204),
('seed_sugg_208', NULL, 'sugar_bp', 'Monitor your blood sugar and BP regularly and keep a log.', 'Monitor your blood sugar and BP regularly and keep a log.', '🥗', 209);

INSERT INTO tasks_exercise (id, user_id, condition_key, name, tip, icon, display_order) VALUES 
('seed_sugg_108', NULL, 'general', 'Do at least 30-45 minutes of brisk walking or moderate cardio daily.', 'Do at least 30-45 minutes of brisk walking or moderate cardio daily.', '🏃', 109),
('seed_sugg_109', NULL, 'general', 'Practice basic yoga stretching', 'Practice basic yoga stretching (Surya Namaskar) for flexibility and blood flow.', '🏃', 110),
('seed_sugg_111', NULL, 'general', 'Engage in strength exercises 2-3 times a week to maintain muscle mass.', 'Engage in strength exercises 2-3 times a week to maintain muscle mass.', '🏃', 112),
('seed_sugg_124', NULL, 'digestion', 'Take a slow 15-minute gentle walk after meals to aid peristalsis.', 'Take a slow 15-minute gentle walk after meals to aid peristalsis.', '🏃', 125),
('seed_sugg_127', NULL, 'digestion', 'Avoid rigorous high-intensity cardio immediately after eating.', 'Avoid rigorous high-intensity cardio immediately after eating.', '🏃', 128),
('seed_sugg_140', NULL, 'weight', 'Aim for 45-60 minutes of brisk walking', 'Aim for 45-60 minutes of brisk walking, jogging, or cycling.', '🏃', 141),
('seed_sugg_141', NULL, 'weight', 'Incorporate resistance training or bodyweight exercises', 'Incorporate resistance training or bodyweight exercises (squats, pushups) to build muscle.', '🏃', 142),
('seed_sugg_156', NULL, 'stress', 'Practice calming yoga postures', 'Practice calming yoga postures (Balasana, Savasana, Forward bends).', '🏃', 157),
('seed_sugg_157', NULL, 'stress', 'Engage in 20-30 minutes of gentle walking in nature', 'Engage in 20-30 minutes of gentle walking in nature (green spaces).', '🏃', 158),
('seed_sugg_159', NULL, 'stress', 'Avoid overly exhaustive', 'Avoid overly exhaustive, competitive workouts if already mentally drained.', '🏃', 160),
('seed_sugg_172', NULL, 'sleep', 'Do light', 'Do light, restorative yoga or gentle stretching before getting into bed.', '🏃', 173),
('seed_sugg_175', NULL, 'sleep', 'Avoid vigorous', 'Avoid vigorous, heart-pumping cardio within 3 hours of your bedtime.', '🏃', 176),
('seed_sugg_188', NULL, 'joints', 'Engage in low-impact exercises like swimming', 'Engage in low-impact exercises like swimming, cycling, or flat-ground walking.', '🏃', 189),
('seed_sugg_189', NULL, 'joints', 'Perform gentle range-of-motion stretching daily to prevent stiffness.', 'Perform gentle range-of-motion stretching daily to prevent stiffness.', '🏃', 190),
('seed_sugg_194', NULL, 'joints', 'Take frequent breaks to stretch if you have a desk job.', '', '🏃', 195),
('seed_sugg_204', NULL, 'sugar_bp', 'Aim for 150 minutes of moderate aerobic exercise', 'Aim for 150 minutes of moderate aerobic exercise (brisk walking) per week.', '🏃', 205),
('seed_sugg_205', NULL, 'sugar_bp', 'Take a 10-15 minute light walk after every major meal to lower glucose spikes.', 'Take a 10-15 minute light walk after every major meal to lower glucose spikes.', '🏃', 206),
('seed_sugg_207', NULL, 'sugar_bp', 'Practice stress-reducing yoga and deep breathing to manage BP.', 'Practice stress-reducing yoga and deep breathing to manage BP.', '🏃', 208);

INSERT INTO tasks_mental (id, user_id, condition_key, name, tip, icon, display_order) VALUES 
('seed_sugg_113', NULL, 'general', 'Practice 10-15 minutes of mindfulness or meditation to manage daily stress.', 'Practice 10-15 minutes of mindfulness or meditation to manage daily stress.', '🧘', 114),
('seed_sugg_119', NULL, 'digestion', 'Chew food thoroughly', 'Chew food thoroughly (25-30 times) and eat mindfully without rushing.', '🧘', 120),
('seed_sugg_130', NULL, 'digestion', 'Manage stress', 'Manage stress, as anxiety directly impacts the gut-brain axis.', '🧘', 131),
('seed_sugg_144', NULL, 'weight', 'Eat mindfully and slowly', 'Eat mindfully and slowly; it takes 20 minutes for the brain to register fullness.', '🧘', 145),
('seed_sugg_148', NULL, 'stress', 'Consume magnesium-rich foods', 'Consume magnesium-rich foods (almonds, spinach, pumpkin seeds) to calm nerves.', '🧘', 149),
('seed_sugg_150', NULL, 'stress', 'Drink calming herbal teas like chamomile', 'Drink calming herbal teas like chamomile, ashwagandha, or tulsi.', '🧘', 151),
('seed_sugg_153', NULL, 'stress', 'Limit alcohol and smoking', 'Limit alcohol and smoking, as they ultimately increase physiological stress.', '🛑', 154),
('seed_sugg_162', NULL, 'stress', 'Take small 5-minute ''breathe'' breaks every 2 hours during the workday.', 'Take small 5-minute ''breathe'' breaks every 2 hours during the workday.', '🧘', 163),
('seed_sugg_174', NULL, 'sleep', 'Practice progressive muscle relaxation while lying in bed.', 'Practice progressive muscle relaxation while lying in bed.', '🧘', 175),
('seed_sugg_179', NULL, 'sleep', 'Read a physical book or listen to calm music as a pre-sleep wind-down routine.', 'Read a physical book or listen to calm music as a pre-sleep wind-down routine.', '🧘', 180),
('seed_sugg_192', NULL, 'joints', 'Maintain a healthy body weight to reduce mechanical stress on knees and hips.', 'Maintain a healthy body weight to reduce mechanical stress on knees and hips.', '🧘', 193),
('seed_sugg_210', NULL, 'sugar_bp', 'Manage stress actively', 'Manage stress actively, as cortisol and adrenaline spike both BP and sugar.', '🧘', 211);

INSERT INTO tasks_sleep (id, user_id, condition_key, name, tip, icon, display_order) VALUES 
('seed_sugg_107', NULL, 'general', 'Limit late-night heavy meals that disrupt sleep and digestion.', 'Limit late-night heavy meals that disrupt sleep and digestion.', '🛑', 108),
('seed_sugg_112', NULL, 'general', 'Maintain a consistent sleep schedule (7-8 hours).', '', '🌙', 113),
('seed_sugg_114', NULL, 'general', 'Do a digital detox 1 hour before bedtime.', '', '🌙', 115),
('seed_sugg_146', NULL, 'weight', 'Ensure 7-8 hours of sleep', 'Ensure 7-8 hours of sleep; sleep deprivation spikes hunger hormones (Ghrelin).', '🌙', 147),
('seed_sugg_164', NULL, 'sleep', 'Drink a glass of warm milk', 'Drink a glass of warm milk (optionally with a pinch of nutmeg) before bed.', '🌙', 165),
('seed_sugg_165', NULL, 'sleep', 'Eat a light', 'Eat a light, easily digestible dinner at least 2-3 hours before sleeping.', '🌙', 166),
('seed_sugg_170', NULL, 'sleep', 'Do not consume alcohol before bed', 'Do not consume alcohol before bed; it disrupts REM sleep architecture.', '🛑', 171),
('seed_sugg_171', NULL, 'sleep', 'Avoid drinking excess fluids right before bed to prevent night-time waking.', 'Avoid drinking excess fluids right before bed to prevent night-time waking.', '🛑', 172),
('seed_sugg_173', NULL, 'sleep', 'Engage in regular daytime physical activity to build sleep pressure.', 'Engage in regular daytime physical activity to build sleep pressure.', '🌙', 174),
('seed_sugg_176', NULL, 'sleep', 'Maintain a cool', 'Maintain a cool, completely dark, and quiet bedroom environment.', '🌙', 177),
('seed_sugg_177', NULL, 'sleep', 'Strictly stop using all screens', 'Strictly stop using all screens (phones, TV) 1 hour before bed (blue light).', '🌙', 178),
('seed_sugg_178', NULL, 'sleep', 'Follow a consistent sleep schedule', 'Follow a consistent sleep schedule, waking up at the same time daily.', '🌙', 179),
('seed_sugg_209', NULL, 'sugar_bp', 'Take prescribed medications on time without skipping doses.', 'Take prescribed medications on time without skipping doses.', '🌙', 210);

INSERT INTO tasks_habits (id, user_id, condition_key, name, tip, icon, display_order) VALUES 
('seed_sugg_100', NULL, 'general', 'Fill half your plate with colorful vegetables and fruits', 'Fill half your plate with colorful vegetables and fruits (50/25/25 rule).', '✨', 101),
('seed_sugg_110', NULL, 'general', 'Use stairs instead of elevators and stay active throughout the workday.', 'Use stairs instead of elevators and stay active throughout the workday.', '✨', 111),
('seed_sugg_115', NULL, 'general', 'Wash your hands frequently and maintain basic hygiene.', '', '✨', 116),
('seed_sugg_121', NULL, 'digestion', 'Avoid raw salads and heavy beans at night as they increase bloating', 'Avoid raw salads and heavy beans at night as they increase bloating (Vata).', '🛑', 122),
('seed_sugg_126', NULL, 'digestion', 'Do gentle abdominal twists or Pawanmuktasana on an empty stomach.', 'Do gentle abdominal twists or Pawanmuktasana on an empty stomach.', '✨', 127),
('seed_sugg_128', NULL, 'digestion', 'Leave 1/4th of your stomach empty for digestive gases to move.', 'Leave 1/4th of your stomach empty for digestive gases to move.', '✨', 129),
('seed_sugg_135', NULL, 'weight', 'Include natural metabolism boosters like ginger', 'Include natural metabolism boosters like ginger, lemon, and cinnamon.', '✨', 136),
('seed_sugg_137', NULL, 'weight', 'Cut out liquid calories', 'Cut out liquid calories (sweetened sodas, packaged fruit juices).', '🛑', 138),
('seed_sugg_138', NULL, 'weight', 'Avoid late-night snacking', 'Avoid late-night snacking, ensuring a 12-hour gap between dinner and breakfast.', '🛑', 139),
('seed_sugg_142', NULL, 'weight', 'Include High-Intensity Interval Training', 'Include High-Intensity Interval Training (HIIT) 2 times a week.', '✨', 143),
('seed_sugg_143', NULL, 'weight', 'Avoid sitting continuously for more than 45 minutes', 'Avoid sitting continuously for more than 45 minutes; take micro-breaks.', '✨', 144),
('seed_sugg_145', NULL, 'weight', 'Track your portion sizes without extreme starvation or crash diets.', 'Track your portion sizes without extreme starvation or crash diets.', '✨', 146),
('seed_sugg_147', NULL, 'weight', 'Keep healthy snacks', 'Keep healthy snacks (nuts, roasted chana) handy to avoid junk cravings.', '✨', 148),
('seed_sugg_160', NULL, 'stress', 'Set strict boundaries for work hours and avoid checking emails late at night.', 'Set strict boundaries for work hours and avoid checking emails late at night.', '✨', 161),
('seed_sugg_161', NULL, 'stress', 'Practice gratitude journaling or talk to a trusted friend/therapist.', 'Practice gratitude journaling or talk to a trusted friend/therapist.', '✨', 162),
('seed_sugg_163', NULL, 'stress', 'Limit consumption of negative news and toxic social media.', 'Limit consumption of negative news and toxic social media.', '✨', 164),
('seed_sugg_169', NULL, 'sleep', 'Avoid heavy', 'Avoid heavy, spicy, or high-fat dinners that cause acid reflux when lying down.', '🛑', 170),
('seed_sugg_180', NULL, 'joints', 'Include anti-inflammatory spices like turmeric', 'Include anti-inflammatory spices like turmeric (with black pepper) and ginger.', '✨', 181),
('seed_sugg_182', NULL, 'joints', 'Consume Vitamin C rich fruits', 'Consume Vitamin C rich fruits (citrus, amla) for collagen synthesis.', '✨', 183),
('seed_sugg_187', NULL, 'joints', 'Reduce intake of nightshade vegetables', 'Reduce intake of nightshade vegetables (tomatoes, eggplant) if they trigger you.', '🛑', 188),
('seed_sugg_190', NULL, 'joints', 'Strengthen the muscles around the joints', 'Strengthen the muscles around the joints (e.g., quadriceps for knee support).', '✨', 191),
('seed_sugg_191', NULL, 'joints', 'Avoid high-impact jumping', 'Avoid high-impact jumping, heavy lifting, or running on hard concrete.', '✨', 192),
('seed_sugg_193', NULL, 'joints', 'Apply warm compresses for chronic stiffness', 'Apply warm compresses for chronic stiffness, or ice packs for acute swelling.', '✨', 194),
('seed_sugg_195', NULL, 'joints', 'Wear supportive, well-cushioned footwear.', '', '✨', 196),
('seed_sugg_198', NULL, 'sugar_bp', 'Consume plenty of soluble fiber', 'Consume plenty of soluble fiber (methi seeds, oats) to slow glucose absorption.', '✨', 199),
('seed_sugg_202', NULL, 'sugar_bp', 'Avoid saturated trans fats found in baked goods and deep-fried items.', 'Avoid saturated trans fats found in baked goods and deep-fried items.', '🛑', 203),
('seed_sugg_206', NULL, 'sugar_bp', 'Incorporate light resistance training to improve muscle insulin sensitivity.', 'Incorporate light resistance training to improve muscle insulin sensitivity.', '✨', 207),
('seed_sugg_211', NULL, 'sugar_bp', 'Stay well-hydrated to help kidneys flush out excess blood glucose.', 'Stay well-hydrated to help kidneys flush out excess blood glucose.', '✨', 212);

