INSERT INTO suggestion_tasks (condition_key, category, name, tip, icon, display_order) VALUES 
('general', 'exercise', 'Morning Brisk Walk', '', '🚶‍♂️', 0),
('general', 'exercise', 'Bodyweight Squats & Full Body Stretch', '', '🤸', 1),
('general', 'exercise', 'Deep Breathing & Pranayama', '', '🫁', 2),
('general', 'food', 'Fill half your plate with colorful vegetables and fruits (50/25/25 rule).', 'Recommended for General Wellness & Daily Vitality', '🥗', 3),
('general', 'food', 'Drink 8-10 glasses (2.5 to 3 Liters) of clean, fresh water across the day.', 'Recommended for General Wellness & Daily Vitality', '🥗', 4),
('general', 'food', 'Incorporate whole grains (brown rice, oats, whole wheat) and sprouted legumes.', 'Recommended for General Wellness & Daily Vitality', '🥗', 5),
('general', 'food', 'Prefer balanced, freshly cooked wholesome home meals.', 'Recommended for General Wellness & Daily Vitality', '🥗', 6),
('general', 'habits', 'Avoid: Avoid deep-fried fast food, heavy oily snacks, and packaged junk.', 'Important to avoid for General Wellness & Daily Vitality', '🚫', 7),
('general', 'habits', 'Avoid: Avoid sugary sodas, artificial energy drinks, and excessive white sugar.', 'Important to avoid for General Wellness & Daily Vitality', '🚫', 8),
('general', 'habits', 'Avoid: Avoid digital smartphone and TV screens for 60 minutes before bedtime.', 'Important to avoid for General Wellness & Daily Vitality', '🚫', 9),
('digestion', 'exercise', 'Vajrasana (Thunderbolt Pose)', '', '🧘', 0),
('digestion', 'exercise', 'Shatapadi (Post-Meal 100 Steps Stroll)', '', '🚶', 1),
('digestion', 'exercise', 'Cat-Cow & Pawanmuktasana', '', '🐈', 2),
('digestion', 'food', 'Sip lukewarm fennel (saunf) and cumin (jeera) infused water 20 minutes post meals.', 'Recommended for Acidity, Gas & Bloating Support', '🥗', 3),
('digestion', 'food', 'Eat cooling gut-soothing foods: Papaya, fresh cucumber, pomegranate, and plain fresh buttermilk.', 'Recommended for Acidity, Gas & Bloating Support', '🥗', 4),
('digestion', 'food', 'Chew every single bite 25-30 times to let salivary enzymes break down food thoroughly.', 'Recommended for Acidity, Gas & Bloating Support', '🥗', 5),
('digestion', 'food', 'Opt for light, easily digestible meals: Moong dal khichdi, bottle gourd, and ridge gourd.', 'Recommended for Acidity, Gas & Bloating Support', '🥗', 6),
('digestion', 'habits', 'Avoid: Strictly eliminate excessively spicy gravies, deep-fried snacks, and chili oil.', 'Important to avoid for Acidity, Gas & Bloating Support', '🚫', 7),
('digestion', 'habits', 'Avoid: Never lie down flat within 2 hours of eating—gravity prevents gastric reflux.', 'Important to avoid for Acidity, Gas & Bloating Support', '🚫', 8),
('digestion', 'habits', 'Avoid: Avoid chilled ice water, sodas, and carbonated beverages during meals.', 'Important to avoid for Acidity, Gas & Bloating Support', '🚫', 9),
('weight', 'exercise', 'Fast-Paced Morning Walk', '', '🏃', 0),
('weight', 'exercise', 'Surya Namaskar (Sun Salutations - 6 to 10 rounds)', '', '☀️', 1),
('weight', 'exercise', 'Chair Squats & Core Planks', '', '💪', 2),
('weight', 'food', 'Eat half a plate of raw vegetable salad (cucumber, carrots, leafy greens) before cooked meals.', 'Recommended for Weight Management & Fat Loss', '🥗', 3),
('weight', 'food', 'Ensure high-quality protein in every meal: Sprouts, chickpeas, paneer, tofu, or lentils.', 'Recommended for Weight Management & Fat Loss', '🥗', 4),
('weight', 'food', 'Drink 1 full glass of lukewarm water exactly 20 minutes before meals to moderate appetite.', 'Recommended for Weight Management & Fat Loss', '🥗', 5),
('weight', 'food', 'Replace milky sugary teas with green tea, cinnamon water, or lemon-cumin water.', 'Recommended for Weight Management & Fat Loss', '🥗', 6),
('weight', 'habits', 'Avoid: Zero refined white sugar, sweets, cakes, and sweetened sodas/fruit juices.', 'Important to avoid for Weight Management & Fat Loss', '🚫', 7),
('weight', 'habits', 'Avoid: Avoid late-night dining: Conclude all food intake by 8:00 PM (12-hour gentle fast).', 'Important to avoid for Weight Management & Fat Loss', '🚫', 8),
('weight', 'habits', 'Avoid: Avoid sitting uninterrupted for over 45 minutes—stand up to reactivate fat-burning enzymes.', 'Important to avoid for Weight Management & Fat Loss', '🚫', 9),
('stress', 'exercise', 'Anulom Vilom & Bhramari Pranayama', '', '🧘‍♂️', 0),
('stress', 'exercise', '4-7-8 Deep Relaxation Breathing', '', '🌬️', 1),
('stress', 'exercise', 'Peaceful Nature Walk (No Screen)', '', '🌳', 2),
('stress', 'food', 'Prioritize magnesium & omega-3 foods: Walnuts, pumpkin seeds, soaked almonds, and bananas.', 'Recommended for Stress, Anxiety & Mental Fatigue Support', '🥗', 3),
('stress', 'food', 'Sip warm chamomile, peppermint, or lavender herbal tea in the afternoon.', 'Recommended for Stress, Anxiety & Mental Fatigue Support', '🥗', 4),
('stress', 'food', 'Eat slowly in a calm, screen-free environment with mindful appreciation.', 'Recommended for Stress, Anxiety & Mental Fatigue Support', '🥗', 5),
('stress', 'food', 'Enjoy fresh berries and a small square of 70%+ dark chocolate for antioxidant mood support.', 'Recommended for Stress, Anxiety & Mental Fatigue Support', '🥗', 6),
('stress', 'habits', 'Avoid: Zero caffeine (coffee, strong tea, energy drinks) after 12:00 PM noon.', 'Important to avoid for Stress, Anxiety & Mental Fatigue Support', '🚫', 7),
('stress', 'habits', 'Avoid: Avoid stressful doomscrolling, sensationalist news feeds, and social comparison.', 'Important to avoid for Stress, Anxiety & Mental Fatigue Support', '🚫', 8),
('stress', 'habits', 'Avoid: Avoid eating during emotional stress, rush, or heated arguments.', 'Important to avoid for Stress, Anxiety & Mental Fatigue Support', '🚫', 9),
('sleep', 'exercise', 'Viparita Karani (Legs-Up-The-Wall Pose)', '', '🛏️', 0),
('sleep', 'exercise', 'Balasana (Child''s Pose) & Neck Stretch', '', '🌙', 1),
('sleep', 'exercise', 'Morning Natural Daylight Walk', '', '🌅', 2),
('sleep', 'food', 'Eat light, easy-to-digest dinners: Moong dal khichdi, warm pumpkin soup, or steamed vegetables.', 'Recommended for Insomnia & Restless Sleep Support', '🥗', 3),
('sleep', 'food', 'Bedtime tryptophan booster: Half a cup of warm milk or 4-5 soaked almonds 30m before bed.', 'Recommended for Insomnia & Restless Sleep Support', '🥗', 4),
('sleep', 'food', 'Strict 2:00 PM caffeine curfew: Zero coffee, black tea, energy drinks, or colas.', 'Recommended for Insomnia & Restless Sleep Support', '🥗', 5),
('sleep', 'food', 'Taper evening fluid intake after 7:00 PM to avoid nighttime awakenings.', 'Recommended for Insomnia & Restless Sleep Support', '🥗', 6),
('sleep', 'habits', 'Avoid: Strictly no smartphones, tablets, or laptops in bed—blue light halts melatonin production.', 'Important to avoid for Insomnia & Restless Sleep Support', '🚫', 7),
('sleep', 'habits', 'Avoid: Avoid afternoon coffee, tea, or chocolate past 2:00 PM (caffeine has a 6-hour half-life).', 'Important to avoid for Insomnia & Restless Sleep Support', '🚫', 8),
('sleep', 'habits', 'Avoid: Avoid heavy, oily, spicy dinners within 3 hours of your planned sleep time.', 'Important to avoid for Insomnia & Restless Sleep Support', '🚫', 9),
('joints', 'exercise', 'Bhujangasana & Gentle Cat-Cow Spine Flow', '', '🦎', 0),
('joints', 'exercise', 'Seated Knee Extensions & Ankle Rotations', '', '🪑', 1),
('joints', 'exercise', 'Gentle Flat-Surface Walking', '', '👟', 2),
('joints', 'food', 'Golden turmeric milk (with a pinch of black pepper for curcumin absorption) daily.', 'Recommended for Back Strain, Neck Tension & Joint Stiffness', '🥗', 3),
('joints', 'food', 'Incorporate anti-inflammatory omega-3 sources: Walnuts, ground flaxseeds, and chia seeds.', 'Recommended for Back Strain, Neck Tension & Joint Stiffness', '🥗', 4),
('joints', 'food', 'Ensure sufficient Calcium and Vitamin D3 (morning sunlight exposure) for skeletal strength.', 'Recommended for Back Strain, Neck Tension & Joint Stiffness', '🥗', 5),
('joints', 'food', 'Drink ample water: Cartilage and spinal discs are 80% water and require fluid to cushion.', 'Recommended for Back Strain, Neck Tension & Joint Stiffness', '🥗', 6),
('joints', 'habits', 'Avoid: Avoid sitting continuously for over 40 minutes—set a standing/walking reminder.', 'Important to avoid for Back Strain, Neck Tension & Joint Stiffness', '🚫', 7),
('joints', 'habits', 'Avoid: Avoid slumping your neck over phones (''tech neck'' puts 50 lbs of cervical pressure).', 'Important to avoid for Back Strain, Neck Tension & Joint Stiffness', '🚫', 8),
('joints', 'habits', 'Avoid: Avoid overly soft, sagging mattresses or extra thick pillows that twist the spine.', 'Important to avoid for Back Strain, Neck Tension & Joint Stiffness', '🚫', 9),
('sugar_bp', 'exercise', 'Post-Meal Blood Glucose Walk', '', '🚶‍♂️', 0),
('sugar_bp', 'exercise', 'Isometric Wall Sits (BP Reducer)', '', '🧱', 1),
('sugar_bp', 'exercise', 'Nadi Shodhana Pranayama (Alternate Nostril)', '', '🧘', 2),
('sugar_bp', 'food', 'Base meals on low-glycemic, fiber-rich whole foods: Rolled oats, millets, beans, and lentils.', 'Recommended for Blood Sugar & Blood Pressure Support', '🥗', 3),
('sugar_bp', 'food', 'Morning ritual: Soak 1 teaspoon of fenugreek (methi) seeds in warm water overnight; drink on empty stomach.', 'Recommended for Blood Sugar & Blood Pressure Support', '🥗', 4),
('sugar_bp', 'food', 'Lower sodium intake: Use potassium-rich vegetables (spinach, cucumber) and herbal seasonings instead of salt.', 'Recommended for Blood Sugar & Blood Pressure Support', '🥗', 5),
('sugar_bp', 'food', 'Add cinnamon powder or fresh amla (Indian gooseberry) for natural glycemic balance.', 'Recommended for Blood Sugar & Blood Pressure Support', '🥗', 6),
('sugar_bp', 'habits', 'Avoid: Strictly eliminate refined white sugar, sugary confectionery, bakery pastries, and fruit juice drinks.', 'Important to avoid for Blood Sugar & Blood Pressure Support', '🚫', 7),
('sugar_bp', 'habits', 'Avoid: Avoid high-sodium packaged snacks: Potato chips, processed namkeen, salted nuts, and pickles.', 'Important to avoid for Blood Sugar & Blood Pressure Support', '🚫', 8),
('sugar_bp', 'habits', 'Avoid: Avoid skipping prescribed doctor consultations or daily monitoring logs.', 'Important to avoid for Blood Sugar & Blood Pressure Support', '🚫', 9),
('general', 'mental', '10 Min Meditation', 'Calms the mind and reduces stress', '🧘', 100),
('general', 'sleep', 'Digital Detox 1hr before bed', 'Improves sleep quality and REM cycles', '🌙', 101),
('general', 'sleep', '8 Hours Sleep', 'Essential for body recovery and repair', '😴', 102),
('general', 'habits', 'Drink 8 glasses of water', 'Maintains hydration and flushes toxins', '💧', 103),
('digestion', 'mental', '10 Min Meditation', 'Calms the mind and reduces stress', '🧘', 100),
('digestion', 'sleep', 'Digital Detox 1hr before bed', 'Improves sleep quality and REM cycles', '🌙', 101),
('digestion', 'sleep', '8 Hours Sleep', 'Essential for body recovery and repair', '😴', 102),
('digestion', 'habits', 'Drink 8 glasses of water', 'Maintains hydration and flushes toxins', '💧', 103),
('weight', 'mental', '10 Min Meditation', 'Calms the mind and reduces stress', '🧘', 100),
('weight', 'sleep', 'Digital Detox 1hr before bed', 'Improves sleep quality and REM cycles', '🌙', 101),
('weight', 'sleep', '8 Hours Sleep', 'Essential for body recovery and repair', '😴', 102),
('weight', 'habits', 'Drink 8 glasses of water', 'Maintains hydration and flushes toxins', '💧', 103),
('stress', 'mental', '10 Min Meditation', 'Calms the mind and reduces stress', '🧘', 100),
('stress', 'sleep', 'Digital Detox 1hr before bed', 'Improves sleep quality and REM cycles', '🌙', 101),
('stress', 'sleep', '8 Hours Sleep', 'Essential for body recovery and repair', '😴', 102),
('stress', 'habits', 'Drink 8 glasses of water', 'Maintains hydration and flushes toxins', '💧', 103),
('sleep', 'mental', '10 Min Meditation', 'Calms the mind and reduces stress', '🧘', 100),
('sleep', 'sleep', 'Digital Detox 1hr before bed', 'Improves sleep quality and REM cycles', '🌙', 101),
('sleep', 'sleep', '8 Hours Sleep', 'Essential for body recovery and repair', '😴', 102),
('sleep', 'habits', 'Drink 8 glasses of water', 'Maintains hydration and flushes toxins', '💧', 103),
('joints', 'mental', '10 Min Meditation', 'Calms the mind and reduces stress', '🧘', 100),
('joints', 'sleep', 'Digital Detox 1hr before bed', 'Improves sleep quality and REM cycles', '🌙', 101),
('joints', 'sleep', '8 Hours Sleep', 'Essential for body recovery and repair', '😴', 102),
('joints', 'habits', 'Drink 8 glasses of water', 'Maintains hydration and flushes toxins', '💧', 103),
('sugar_bp', 'mental', '10 Min Meditation', 'Calms the mind and reduces stress', '🧘', 100),
('sugar_bp', 'sleep', 'Digital Detox 1hr before bed', 'Improves sleep quality and REM cycles', '🌙', 101),
('sugar_bp', 'sleep', '8 Hours Sleep', 'Essential for body recovery and repair', '😴', 102),
('sugar_bp', 'habits', 'Drink 8 glasses of water', 'Maintains hydration and flushes toxins', '💧', 103);
